[[level]]
id = "level_001"
file = "level_001.json"
author = "gsnake"
solved = true
difficulty = "easy"
tags = []
description = "First Steps"

[[level]]
id = "level_002"
file = "level_002.json"
author = "gsnake"
solved = true
difficulty = "easy"
tags = []
description = "Floating Drop"

[[level]]
id = "level_003"
file = "level_003.json"
author = "gsnake"
solved = true
difficulty = "easy"
tags = []
description = "Food Bridge"
