[[level]]
id = "level-1769977122223-g36bwe"
file = "level-1769977122223-g36bwe.json"
author = "gsnake"
solved = true
difficulty = "easy"
tags = []
description = "Floating Spike Islands Dense"

[[level]]
id = "level-1769978263873-eupaj5"
file = "level-1769978263873-eupaj5.json"
author = "gsnake"
solved = true
difficulty = "easy"
tags = []
description = "Stone Spike Bridge"
