[[level]]
id = "level_001"
file = "level_001.json"
author = "gsnake"
solved = true
difficulty = "hard"
tags = []
description = "Spike Weave"

[[level]]
id = "level_002"
file = "level_002.json"
author = "gsnake"
solved = true
difficulty = "hard"
tags = []
description = "Gauntlet"

[[level]]
id = "level_003"
file = "level_003.json"
author = "gsnake"
solved = true
difficulty = "hard"
tags = []
description = "Spiked Lift"

[[level]]
id = "level_004"
file = "level_004.json"
author = "gsnake"
solved = true
difficulty = "hard"
tags = []
description = "Food Perch"
