[[level]]
id = "level_001"
file = "level_001.json"
author = "gsnake"
solved = true
difficulty = "hard"
tags = []
description = "The Tower"

[[level]]
id = "level_002"
file = "level_002.json"
author = "gsnake"
solved = true
difficulty = "hard"
tags = []
description = "Floating Islands"
