[[level]]
id = "level_001"
file = "level_001.json"
author = "gsnake"
solved = true
difficulty = "medium"
tags = []
description = "Stone Run"

[[level]]
id = "level_002"
file = "level_002.json"
author = "gsnake"
solved = true
difficulty = "medium"
tags = []
description = "Mixed Signals"
