[[level]]
id = "level-1769975926647-nv3aqb"
file = "level-1769975926647-nv3aqb.json"
author = "gsnake"
solved = true
difficulty = "medium"
tags = []
description = "Floating Stone Spike Islands"

[[level]]
id = "level-1769976243963-g777pk"
file = "level-1769976243963-g777pk.json"
author = "gsnake"
solved = true
difficulty = "medium"
tags = []
description = "Floating Spike Islands Dense 2"

[[level]]
id = "level-1769976545160-dvt1ot"
file = "level-1769976545160-dvt1ot.json"
author = "gsnake"
solved = true
difficulty = "medium"
tags = []
description = "Floating Spike Bridge"
