[[level]]
id = "level_001"
file = "level_001.json"
author = "gsnake"
solved = false
difficulty = "medium"
tags = []
description = "The Wall"

[[level]]
id = "level_002"
file = "level_002.json"
author = "gsnake"
solved = false
difficulty = "medium"
tags = []
description = "Zig Zag"
